### ISSUE TITLE
Setup Felice Rest

### ISSUE THREAD

**Issue by erchiggins** [apticity/workforce-logic#54]
Create Associate controller with one get method, create index controller with one get method, modify webapiconfig so that index is default

**Comment by azumari** [comment]
Branch created
Index Controller added
Pull request opened

**Comment by azumari** [comment]
'Hello World' string added to Associate Controller for testing
'Hello World' string added to Index Controller for testing

**Comment by azumari** [comment]
Index controller set as default controller in WebApiConfig

**Comment by azumari** [comment]
Web.config encrypted as per @fredbelotte instructions.
@erchiggins branch is now ready for review
